[2013-08-07 09:45:46,625] Add tasks
[2013-08-07 09:45:46,630] [ 0] Thread is started.
[2013-08-07 09:45:46,638] [ 0] www.gov.cn: 202.108.251.165
[2013-08-07 09:45:46,638] [ 0] www.gov.cn: 111.161.38.51
[2013-08-07 09:45:46,638] [ 0] www.gov.cn: 124.202.162.148
[2013-08-07 09:45:46,638] [ 0] www.gov.cn: 125.39.191.164
[2013-08-07 09:45:46,646] [ 0] www.xinhuanet.com: 124.202.162.148
[2013-08-07 09:45:46,646] [ 0] www.xinhuanet.com: 125.39.191.164
[2013-08-07 09:45:46,646] [ 0] www.xinhuanet.com: 202.108.251.165
[2013-08-07 09:45:46,646] [ 0] www.xinhuanet.com: 111.161.38.51
[2013-08-07 09:45:46,648] [ 0] www.ctrip.com: 140.207.228.30
[2013-08-07 09:45:46,730] Start to save the result...
[2013-08-07 09:45:46,732] Traceback (most recent call last):
  File "nslookup_daemon.py", line 129, in <module>
    saveResult()
  File "nslookup_daemon.py", line 101, in saveResult
    updater.execute(insert, (ip, row[3], row[4]))
  File "/usr/lib/python2.6/site-packages/mysql/connector/cursor.py", line 392, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python2.6/site-packages/mysql/connector/connection.py", line 584, in cmd_query
    statement))
  File "/usr/lib/python2.6/site-packages/mysql/connector/connection.py", line 506, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1146 (42S02): Table 'cdnlab.cdn_ips' doesn't exist
Traceback (most recent call last):
  File "nslookup_daemon.py", line 129, in <module>
    saveResult()
  File "nslookup_daemon.py", line 101, in saveResult
    updater.execute(insert, (ip, row[3], row[4]))
  File "/usr/lib/python2.6/site-packages/mysql/connector/cursor.py", line 392, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python2.6/site-packages/mysql/connector/connection.py", line 584, in cmd_query
    statement))
  File "/usr/lib/python2.6/site-packages/mysql/connector/connection.py", line 506, in _handle_result
    raise errors.get_exception(packet)
ProgrammingError: 1146 (42S02): Table 'cdnlab.cdn_ips' doesn't exist
[2013-08-07 09:45:46,733] The process is terminated with an exception.
[2013-08-07 09:45:46,733] Start to save the result...
[2013-08-07 09:45:46,734] Results are saved.
[2013-08-07 09:46:55,835] Add tasks
[2013-08-07 09:46:55,839] [ 0] Thread is started.
[2013-08-07 09:46:55,849] [ 0] www.gov.cn: 124.202.162.148
[2013-08-07 09:46:55,849] [ 0] www.gov.cn: 125.39.191.164
[2013-08-07 09:46:55,849] [ 0] www.gov.cn: 202.108.251.165
[2013-08-07 09:46:55,849] [ 0] www.gov.cn: 111.161.38.51
[2013-08-07 09:46:55,853] [ 0] www.xinhuanet.com: 111.161.38.51
[2013-08-07 09:46:55,853] [ 0] www.xinhuanet.com: 124.202.162.148
[2013-08-07 09:46:55,853] [ 0] www.xinhuanet.com: 125.39.191.164
[2013-08-07 09:46:55,853] [ 0] www.xinhuanet.com: 202.108.251.165
[2013-08-07 09:46:55,857] [ 0] www.ctrip.com: 140.207.228.30
[2013-08-07 09:46:55,939] Start to save the result...
[2013-08-07 09:46:56,751] Add tasks
[2013-08-07 09:46:56,753] Start to save the result...
[2013-08-07 09:46:56,754] The process is done normally.
