[2013-08-07 19:01:02,048]CRITICAL: [ 0] The job 116 is terminated with an exception.
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
