[2013-08-07 13:01:31,748] Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 68, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 56, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 68, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 56, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 13:01:31,748] [ 0] The job 62 is terminated with an exception.
[2013-08-07 13:01:51,812] Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 68, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 56, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 68, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 56, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 13:01:51,812] [ 0] The job 110 is terminated with an exception.
[2013-08-07 13:39:51,255] Traceback (most recent call last):
  File "nslookup_daemon.py", line 133, in <module>
    queue.join()
  File "/usr/lib64/python2.6/Queue.py", line 82, in join
    self.all_tasks_done.wait()
  File "/usr/lib64/python2.6/threading.py", line 239, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "nslookup_daemon.py", line 133, in <module>
    queue.join()
  File "/usr/lib64/python2.6/Queue.py", line 82, in join
    self.all_tasks_done.wait()
  File "/usr/lib64/python2.6/threading.py", line 239, in wait
    waiter.acquire()
KeyboardInterrupt
[2013-08-07 13:39:51,256] The process is terminated with an exception.
[2013-08-07 13:46:44,210] [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 14:01:44,398] [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 16:01:21,713] Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 16:01:21,713] [ 0] The job 113 is terminated with an exception.
[2013-08-07 16:03:04,237] [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 17:01:21,966] [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 17:01:42,037] Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 17:01:42,037] [ 0] The job 114 is terminated with an exception.
[2013-08-07 17:02:39,504] Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 17:02:39,505] [ 0] The job 450 is terminated with an exception.
[2013-08-07 18:02:28,983]CRITICAL: [ 0] The job 427 is terminated with an exception.
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 20:01:31,560]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 20:01:51,732]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 20:02:30,254]CRITICAL: [ 0] The job 381 is terminated with an exception.
Traceback (most recent call last):
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 73, in nslookup
    ips = runCheck(i, domain)
  File "/home/cdnlab-gnp/gnp-deploy/nslookup_daemon.py", line 57, in runCheck
    result = socket.gethostbyname_ex(host)
herror: [Errno 2] Host name lookup failure
[2013-08-07 20:02:59,655]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 21:02:02,153]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 21:02:32,183]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 21:02:54,094]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
[2013-08-07 22:01:32,378]WARNING: [ 0] An error occurs when handling the runCheck: [Errno -3] Temporary failure in name resolution
